#+TITLE: ELEC1111 - Electrical and Telecommunications Engineering
#+LATEX_CLASS: article
#+OPTIONS: toc:nil
* <2017-07-28 Fri> Basic Concepts                              :definitions:
 [[file:lectures/lecture1.pdf][Lecture Slides]]
** Charge
*Electrical charge* is a property of the atomic particles inside matter. It
is measured in coulombs (C). Charge is always found in multiples of
electrons. /The Law of Conservation of Charge/ states that charge can
neither be created nor destroyed, only transferred.
** Current
*Current* is the movement of electronic charge. In metallic conductors,
current is created by negatively-charged electrons. Practically, both
negative and positive charges are moving when compelled by an electromotive
force. By convention, the direction of current is the net flow of positive
charge. Mathematically, it is the rate of change of charge per unit time
through an element. \begin{equation} i = \frac{dq}{dt} \end{equation} Charge
transferred over a period of time: \begin{equation} Q = \int_{t_0}^{t_1} i
dt \end{equation}

*Direct Current* is defined as current that only flows in one direction. It
can be constant or time varying. *Alternating Current* is current that
changes direction over time. Current is a two dimensional variable,
described by value and direction.
** Voltage
Electrons move when there is a *potential difference* of charge between two
locations. It is defined as the energy required to move a unit of charge
from a reference point to another point through an element by an external
electromotive force. \begin{equation} v_a - v_b = v_ab = \frac{dw}{dq}
\end{equation} It has a value and a polarity which can be chosen arbitrarily
in circuits. Voltage can also be AC or DC in the same fashion as current. 

Voltage and current alone do not describe the energy consumed by an
electrical element. *Power* is defined as the rate of expending or asorbing
energy per unit of time. \begin{equation} p = \frac{dw}{dt} \newline
\end{equation} By the definition of voltage and current we can see
that: \begin{equation} p = vi \end{equation}
** Power
Power obeys a sign convention determined by the direction of current flowing
through an element and the polarity of voltage. Power is positive when
current enters the positive terminal of an element and is negative when
current enters through the negative terminal of the element. *Positive
power* is absorbed or consumed by an element whilst *negative power* is
generated by an element.

By the /Conservation of Energy/ power must be conserved such
that. \begin{equation} \sum p_s = \sum p_a \end{equation}
and \begin{equation} \sum p = 0 \end{equation} *Energy* is the capacity to
do work measured is watt-hours(Wh) where 1 joule = 1
watt-second. \begin{equation} w = \int_{t_0}^{t} p dt \end{equation}
** Circuit
An *electric circuit* is an interconnection of electrical elements. In a
circuit, direction is chosen to be arbitrary. Circuit elements are building
blocks of electric circuits.
| Active Elements            | Passive Elements          |
|----------------------------+---------------------------|
| *Generate or supply power* | *Absorb or consume power* |
| Generators                 | Resistors                 |
| Batteries                  | Capacitors                |
| Operational Amplifiers     | Inductors                 |
An *ideal independent source* is an active element that provides a specified
voltage and current that is completely independent of any other voltage or
current in the circuit. Represented on diagrams as *circles*.
#+ATTR_LATEX: :environment longtable :align p{5cm}p{5cm}
| Ideal Voltage Source                                                   | Ideal Current Source                                                                         |
|------------------------------------------------------------------------+----------------------------------------------------------------------------------------------|
| Has no internal resistance                                             | Has infinite resistance                                                                      |
| Capable of producing any necessary current to maintain desired voltage | Capable of producing any necessary voltage to establish desired current through the terminal |
| Voltage is known at the terminals but current is not                   | Current is known at the terminals but voltage is not                                         |
An *ideal dependent source* is an active element whose output is controlled
by another voltage or current in the circuit. Represented on diagrams as *squares*.

In summary,
- Ideal voltage and current sources can generate infinite power
- Actual voltage sources have an upper current limit (limiting output power)
- Ideal voltage and current sources can absorb infinite power from the circuit.
- Actual current sources hae upper voltage limit.
** Basic units
| Quantity           | Basic Unit | Symbol |
|--------------------+------------+--------|
| Length             | metre      | m      |
| Mass               | kilogram   | kg     |
| Time               | Second     | s      |
| Temperature        | Kelvin     | K      |
| Current            | Ampere     | A      |
| Luminous intensity | candela    | Cd     |
** Derived Units [[http:physics.nist.gov/cuu/Units/units.html][Further Reading]] 
| Derived Quantity              | Unit    | Symbol | Expression  |
|-------------------------------+---------+--------+-------------|
| Charge                        | Coulomb | C      | s.A         |
| Electric potential difference | Volt    | V      | J/C  or W/A |
| Resistance                    | Ohm     | \Omega | V/A         |
* <2017-08-02 Wed> Ohm's Law and Kirchoff's Law
** Ohm's law
In a resistor, the voltage across a resistor is directly proportional to the
current flowing through it. \begin{equation} v = Ri \end{equation} So we see
that this constant of proportionality is the resistance R. *Resistance* denotes
the ability of an element to resist the flow of electric current. It is measured
in *Ohms(\Omega)*.

Since resistors are passive elements, Ohm's law conforms to the *passive sign
convention*. Current flows through the higher potential (positive terminal) to a
lower potential (negative terminal).

We can derive two equations for power from Ohm's law. \begin{equation} p = Ri^2
\end{equation} \begin{equation} p = \frac{v^2}{R} \end{equation} Resistors are
passive elements that absorb and dissipate energy. Remember that power
dissipated is always positive.
** Short and Open circuits 
A circuit element with almost *zero resistance* is called a *short circuit*.
Whereas a circuit element with *infinite resistance* is called an *open
circuit*.
| Circuit Type         | Property             |
|----------------------+----------------------|
| Any current may flow | Any voltage may drop |
| E.g. pure wire       | E.g. air gap         |
** Nodes, Branches, Loops/Meshes
| Term   | Definition                               |
|--------+------------------------------------------|
| Branch | Represents a single element              |
| Loop   | Closed path in a circuit                 |
| Mesh   | Loop that contains no other loop         |
| Node   | Point of connection between two branches |

From these terms we can define series and parallel elements. Elements are in
*series* if they exclusively share a single node and consequently carry the same
current. Two or more elements are in parallel if they are connected to the same
two nodes and have the same voltage across them.
** Resistivity and conductance
*Conductance* is the ability of an element to conduct electric current. It is
the reciprocal of resistance. \begin{equation} G=\frac{1}{R}\end{equation}

We can have *linear resistors* (which obey Ohm's Law) and *non-linear*
resistors. Such resistors have a resistance that varies with current giving a
non-linear current-voltage graph.

Materials tend to resist the flow of electricity through them. The resistance of
an object is a function of its length, l and cross sectional area, A and the
material's resitivity \rho. \begin{equation} R = \rho\frac{l}{A} \end{equation}
** Kirchoff's Law
*Kirchoff's Current Law* states that the algebraic sum of all currents entering
 a node or a closed boundary is zero. \begin{equation} \sum_{n=1}^{N} i_n = 0
 \end{equation} This means the sum of currents entering the node = sum of
 currents leaving the node. Consider current *entering* a node to be *positive*
 and current *leaving* a node to be *negative*. It follows that two elements in
 series have the same current.

*Kirchoff's Voltage Law* states that the algebraic sum of all voltages around a
closed path or loop is zero. \begin{equation} \sum_{m=1}^{M} v_m = 0
\end{equation} You may start from any node in the loop and go in either
direction. It follows that two parallel elements have the same voltages. 
*** Problem solving techniques
- Identify all branches, nodes and loops/meshes
- Assign a current for each branch with a *direction*
	- For resistors, use a passive sign convention
	- For voltage sources, use a passive sign convention: current enters from
    negative terminal and leaves the positive terminal
- Assign a voltage across each element and use passive sign convention for
  polarity
	- For resistors, + where current enters
	- For current sources, + where current leaves the source
- Write down *KVL* equations for each loop/mesh
- Write down *KCL* equations for each node
- Write down voltage-current relation for all resistors using *Ohm's Law*
- Solve for unknown parameters


