ELEC1111 - Electrical and Telecommunications Engineering
#+LATEX_CLASS: article
#+OPTIONS: toc:nil
* <2017-07-28 Fri> Basic Concepts                              :definitions:
 [[file:lectures/lecture1.pdf][Lecture Slides]]
** Charge
*Electrical charge* is a property of the atomic particles inside matter. It
is measured in coulombs (C). Charge is always found in multiples of
electrons. /The Law of Conservation of Charge/ states that charge can
neither be created nor destroyed, only transferred.
** Current
*Current* is the movement of electronic charge. In metallic conductors,
current is created by negatively-charged electrons. Practically, both
negative and positive charges are moving when compelled by an electromotive
force. By convention, the direction of current is the net flow of positive
charge. Mathematically, it is the rate of change of charge per unit time
through an element. \begin{equation} i = \frac{dq}{dt} \end{equation} Charge
transferred over a period of time: \begin{equation} Q = \int_{t_0}^{t_1} i
dt \end{equation}

*Direct Current* is defined as current that only flows in one direction. It
can be constant or time varying. *Alternating Current* is current that
changes direction over time. Current is a two dimensional variable,
described by value and direction.
** Voltage
Electrons move when there is a *potential difference* of charge between two
locations. It is defined as the energy required to move a unit of charge
from a reference point to another point through an element by an external
electromotive force. \begin{equation} v_a - v_b = v_ab = \frac{dw}{dq}
\end{equation} It has a value and a polarity which can be chosen arbitrarily
in circuits. Voltage can also be AC or DC in the same fashion as current. 

Voltage and current alone do not describe the energy consumed by an
electrical element. *Power* is defined as the rate of expending or asorbing
energy per unit of time. \begin{equation} p = \frac{dw}{dt} \newline
\end{equation} By the definition of voltage and current we can see
that: \begin{equation} p = vi \end{equation}
** Power
Power obeys a sign convention determined by the direction of current flowing
through an element and the polarity of voltage. Power is positive when
current enters the positive terminal of an element and is negative when
current enters through the negative terminal of the element. *Positive
power* is absorbed or consumed by an element whilst *negative power* is
generated by an element.

By the /Conservation of Energy/ power must be conserved such
that. \begin{equation} \sum p_s = \sum p_a \end{equation}
and \begin{equation} \sum p = 0 \end{equation} *Energy* is the capacity to
do work measured is watt-hours(Wh) where 1 joule = 1
watt-second. \begin{equation} w = \int_{t_0}^{t} p dt \end{equation}
** Circuit
An *electric circuit* is an interconnection of electrical elements. In a
circuit, direction is chosen to be arbitrary. Circuit elements are building
blocks of electric circuits.
| Active Elements            | Passive Elements          |
|----------------------------+---------------------------|
| *Generate or supply power* | *Absorb or consume power* |
| Generators                 | Resistors                 |
| Batteries                  | Capacitors                |
| Operational Amplifiers     | Inductors                 |
An *ideal independent source* is an active element that provides a specified
voltage and current that is completely independent of any other voltage or
current in the circuit. Represented on diagrams as *circles*.
#+ATTR_LATEX: :environment longtable :align p{5cm}p{5cm}
| Ideal Voltage Source                                                   | Ideal Current Source                                                                         |
|------------------------------------------------------------------------+----------------------------------------------------------------------------------------------|
| Has no internal resistance                                             | Has infinite resistance                                                                      |
| Capable of producing any necessary current to maintain desired voltage | Capable of producing any necessary voltage to establish desired current through the terminal |
| Voltage is known at the terminals but current is not                   | Current is known at the terminals but voltage is not                                         |
An *ideal dependent source* is an active element whose output is controlled
by another voltage or current in the circuit. Represented on diagrams as *squares*.

In summary,
- Ideal voltage and current sources can generate infinite power
- Actual voltage sources have an upper current limit (limiting output power)
- Ideal voltage and current sources can absorb infinite power from the circuit.
- Actual current sources hae upper voltage limit.
** Basic units
| Quantity           | Basic Unit | Symbol |
|--------------------+------------+--------|
| Length             | metre      | m      |
| Mass               | kilogram   | kg     |
| Time               | Second     | s      |
| Temperature        | Kelvin     | K      |
| Current            | Ampere     | A      |
| Luminous intensity | candela    | Cd     |
** Derived Units [[http:physics.nist.gov/cuu/Units/units.html][Further Reading]] 
| Derived Quantity              | Unit    | Symbol | Expression  |
|-------------------------------+---------+--------+-------------|
| Charge                        | Coulomb | C      | s.A         |
| Electric potential difference | Volt    | V      | J/C  or W/A |
| Resistance                    | Ohm     | \Omega | V/A         |
* <2017-08-02 Wed> Ohm's Law and Kirchoff's Law
** Resistivity
Materials tend to resist the flow of electricity through them. The resistance of
an object is a function of its length, l and cross sectional area, A and the
material's resitivity \rho.
